DECLARE
 XP NUMBER;
 YP NUMBER;
BEGIN
 XP:= GET_ITEM_PROPERTY('CTL.CAL2',X_POS);
 YP:= GET_ITEM_PROPERTY('CTL.CAL2',Y_POS);
DATE_LOV.GET_DATE(SYSDATE,'CTL.CAL2',XP,YP,'FORM DATE', 'OK', 'CANCEL',TRUE,FALSE,FALSE);
END;
